### ISSUE TITLE
Enable sshd on boot option not working

### ISSUE THREAD

**Issue by 4iTeam** [finnix/finnix#20]
Hello
I have tried to add 
sshd sshd_password=abc123 to boot param on latest version but it doesn't work

Have parameters name changed or this feature removed since we use debian live?

**Comment by WHK102** [comment]
I test rewriting the squashfs and chrooting + `systemctl enable ssh` but does not work.

It is linked to /usr/lib/systemd/system/ssh.service but does not work.

`systemctl status ssh`:

`Loaded: load (/lib/systemd/system/ssh.service; enabled; vendor preset: enabled)`

Check this: **; enabled;** is enabled! but can not autostart!.

**Comment by rfinnie** [comment]
Finnix 120-122 does not have the ability to start sshd from the boot cmdline. This will be supported when 123 is released with: `sshd passwd=abc123`.

**Comment by 4iTeam** [comment]
Thank you rfinnie, pls note that we also need boot param to configure network (static ip or dhcp)

**Comment by MohammadrezaNasrabadi** [comment]
> Finnix 120-122 does not have the ability to start sshd from the boot cmdline. This will be supported when 123 is released with: `sshd passwd=abc123`.

Hi. Could you please help me how exactly did you pass the boot parameter? My finnix version is 125 and I couldn't enable sshd daemon via boot command line.
