### ISSUE TITLE
Can not autostart services

### ISSUE THREAD

**Issue by WHK102** [finnix/finnix#21]
I extract the squashfs and made a chroot on the filesystem, i write a service in `/etc/systemd/system/example.service` and i enable it using `systemctl enable example.service` and made the symbolic link fine.

When pack the squashfs and create the iso again the service can not start but is labeled by **enabled**.

The service is very simple:

```
Description=Example
After=network.target

[Service]
Type=simple
Restart=always
RestartSec=5
User=root
ExecStart=/bin/example-app
WorkingDirectory=/root

[Install]
WantedBy=multi-user.target
```

Journalctl is have not issues for the service, the service can not start.

Similar problem is ssh service: https://github.com/finnix/finnix/issues/20

**Comment by rfinnie** [comment]
The running live target is finnix.target, so you want: `systemctl add-wants finnix.target example.service`, or "WantedBy=finnix.target" in the .service directly. to be able to do `systemctl enable example.service`.

**Comment by WHK102** [comment]
Thanks, with `finnix.target` works fine.
