### ISSUE TITLE
Consider adding neovim

### ISSUE THREAD

**Issue by Silejonu** [finnix/finnix#22]
Neovim is a modernised vim.
https://neovim.io/

**Comment by rfinnie** [comment]
Neovim looks nice, but is relatively large like vim, so I'd rather keep vim.tiny pre-installed.  However, I've added neovim to the `command-not-found` handler as an install suggestion for vim.

**Comment by rfinnie** [comment]
https://blog.finnix.org/2022/03/22/finnix-124-released/
