### ISSUE TITLE
Consider adding gdu

### ISSUE THREAD

**Issue by Silejonu** [finnix/finnix#27]
gdu is a disk analyzer, primarily intended for SSD. It is very similar to ncdu, but a lot faster (5.5 times faster for SSDs).
It is available in Debian 11 repos, but not Debian 10.
https://github.com/dundee/gdu

**Comment by rfinnie** [comment]
Added for Finnix 124, thank you!

**Comment by rfinnie** [comment]
https://blog.finnix.org/2022/03/22/finnix-124-released/
