### ISSUE TITLE
0 kernel parameter not mentioned in docs

### ISSUE THREAD

**Issue by lightonflux** [finnix/finnix#52]
https://github.com/finnix/finnix-docs/blob/main/kernel-command-line.md

I saw the news about the new kernel parameter. But could not find how to use it in the docs above. Is the parameter documented somewhere?

**Comment by rfinnie** [comment]
Added to [kernel-command-line documentation](https://github.com/finnix/finnix-docs/blob/main/kernel-command-line.md), thank you!
